-- Tabelas de Biolinks (Substituindo o 66biolinks)

CREATE TABLE IF NOT EXISTS public.biolinks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(255) UNIQUE NOT NULL,
  title VARCHAR(255),
  description TEXT,
  background_color_one VARCHAR(50),
  background_color_two VARCHAR(50),
  text_color VARCHAR(50) DEFAULT '#ffffff',
  favicon_url VARCHAR(512),
  clicks INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.biolink_blocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  biolink_id BIGINT REFERENCES public.biolinks(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  location_url VARCHAR(512),
  clicks INT DEFAULT 0,
  settings JSONB,
  sort_order INT DEFAULT 0,
  is_enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ativar RLS
ALTER TABLE public.biolinks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.biolink_blocks ENABLE ROW LEVEL SECURITY;

-- Remover políticas antigas se existirem
DROP POLICY IF EXISTS "Leitura Pública de Biolinks" ON public.biolinks;
DROP POLICY IF EXISTS "Leitura Pública de Blocos" ON public.biolink_blocks;

-- Criar Políticas
CREATE POLICY "Leitura Pública de Biolinks" ON public.biolinks FOR SELECT USING (true);
CREATE POLICY "Leitura Pública de Blocos" ON public.biolink_blocks FOR SELECT USING (true);
