-- ============================================================================
-- Antenor & Filhos — Tabela de Harmonizações (Vinhos ↔ Carnes)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.product_pairings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wine_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  meat_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  match_score INT DEFAULT 95,
  pairing_notes TEXT,
  ai_generated BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_wine_meat_pairing UNIQUE (wine_id, meat_id)
);

-- Índices para consultas de alta performance
CREATE INDEX IF NOT EXISTS idx_pairings_wine ON public.product_pairings(wine_id);
CREATE INDEX IF NOT EXISTS idx_pairings_meat ON public.product_pairings(meat_id);

-- Habilita RLS
ALTER TABLE public.product_pairings ENABLE ROW LEVEL SECURITY;

-- Leitura pública para o storefront
DROP POLICY IF EXISTS "Public read product_pairings" ON public.product_pairings;
CREATE POLICY "Public read product_pairings"
  ON public.product_pairings
  FOR SELECT
  TO anon, authenticated
  USING (true);
